slices:
  - sources:
      - model: NousResearch/Nous-Hermes-2-Yi-34B
        layer_range: [0, 60]
      - model: jondurbin/bagel-dpo-34b-v0.2
        layer_range: [0, 60]
merge_method: slerp
base_model: jondurbin/bagel-dpo-34b-v0.2
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: bfloat16
