slices:
  - sources:
      - model: kyujinpy/Sakura-SOLAR-Instruct
        layer_range: [0, 48]
      - model: jeonsworld/CarbonVillain-en-10.7B-v1
        layer_range: [0, 48]
merge_method: slerp
base_model: jeonsworld/CarbonVillain-en-10.7B-v1
parameters:
  t:
    - filter: self_attn
      value: [0, 0.5, 0.3, 0.7, 1]
    - filter: mlp
      value: [1, 0.5, 0.7, 0.3, 0]
    - value: 0.5
dtype: bfloat16
